#!/bin/bash

SERVE_ENDPOINT=$SERVE_ENDPOINT
NUM_OF_ITERATIONS=$NUM_OF_ITERATIONS
SLEEP_TIME=$SLEEP_TIME
while true
do
  curl $SERVE_ENDPOINT/load/$NUM_OF_ITERATIONS/infer/$NUM_OF_INF
  sleep $SLEEP_TIME
done
