ARG ai_chip
ARG model_dir

FROM public.ecr.aws/docker/library/python:latest as base
RUN apt-get update -y --fix-missing
RUN apt-get install -y python3-venv g++ gettext-base
RUN python -m pip install wget
RUN python -m pip install awscli
RUN python -m pip install gradio

FROM base AS assets-amd64-cuda
ENV VAR=cuda

FROM base AS assets-arm64-cuda
ENV VAR=cuda

FROM base AS assets-amd64-neuron
ENV VAR=xla

FROM assets-${ai_chip} AS final
ENV MODEL_DIR=${model_dir}
RUN wget https://sdinfer.s3.us-west-2.amazonaws.com/${MODEL_DIR}_${VAR}.tar.gz -O /model.tar.gz
RUN echo "VAR is equal to ${VAR}"
RUN echo "model_dir is equal to ${MODEL_DIR}"
