FROM $BASE_IMAGE as base

FROM $ASSETS_IMAGE AS assets

FROM base AS model
COPY --from=1 /model.tar.gz /model-assets/model.tar.gz

RUN tar -xvzf /model-assets/model.tar.gz -C /model-assets
RUN ls -l
RUN ls -l /model-assets
RUN apt-get update --fix-missing
RUN apt-get install -y net-tools
COPY * /
RUN mkdir /config
ADD config/main.yaml /config/main.yaml
